- include_tasks: setup-user.yml
# - include_tasks: asdf-install.yml
- include_tasks: asdf-remove.yml
- include_tasks: install-project.yml
# - include_tasks: install-ruby.yml
- include_tasks: install-ruby-system.yml
- include_tasks: service.yml
